## Server Properties
server:
  port: 5000
##Spring Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 200709
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

