## Server Properties
server:
  port: 5000
##Spring Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 200709
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  cors:
    allowedOrigins: http://localhost:3000
#  jwtSecret: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxODg2MjMyNzE3MiIsIm5hbWUiOiJWaWtpbmcgWW91IiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.TCA7twK8dacEVmNow0vTR0HauJwQ2f94GUl7uVLvGxZ9I_HRe4WGQ__G8GddvJZ-fvjKsF_LZX8s-lp09_ZsYQ
  jwtExpirationInMs: 604800000